In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('imdb-top-1000.csv')

In [4]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [7]:
movies.groupby('Genre')

In [9]:
movies.groupby('Genre').sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [10]:
numerical_columns = movies.select_dtypes(include=['number'])

In [11]:
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].sum()

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [12]:
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].mean()

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [14]:
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].min()

           Runtime  IMDB_Rating  No_of_Votes        Gross  Metascore
Genre
Action          45          7.6        25312       3296.0       33.0
Adventure       88          7.6        29999      61001.0       41.0
Animation       71          7.6        25229     128985.0       61.0
Biography       93          7.6        27254      21877.0       48.0
Comedy          68          7.6        26337       1305.0       45.0
Crime           80          7.6        27712       6013.0       47.0
Drama           64          7.6        25088       3600.0       28.0
Family         100          7.8       178731    4000000.0       67.0
Fantasy         76          7.9        57428  337574718.0        NaN
Film-Noir      100          7.8        59556     449191.0       94.0
Horror          71          7.6        27007      89029.0       46.0
Mystery         96          7.6        33982    1035953.0       52.0
Thriller       108          7.8        27733   17550741.0       81.0
Western        132          7.8        65659    5321508.0       69.0

In [15]:
movies.select_dtypes(include='number').columns

Index(['Runtime', 'IMDB_Rating', 'No_of_Votes', 'Gross', 'Metascore'], dtype='object')

In [17]:
movies.select_dtypes(exclude='object').columns

Index(['Runtime', 'IMDB_Rating', 'No_of_Votes', 'Gross', 'Metascore'], dtype='object')

In [21]:
movies.groupby('Genre')['IMDB_Rating'].value_counts().sort_values(ascending=False)

Genre      IMDB_Rating
Drama      8.1            46
           8.0            45
           7.7            43
           7.8            39
Comedy     7.7            35
                          ..
Drama      8.7             1
           9.3             1
Fantasy    8.1             1
Film-Noir  8.1             1
Western    8.8             1
Name: count, Length: 115, dtype: int64

In [22]:
# Find the top 3 genres by total earning
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [24]:
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [31]:
# Alternated method
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [32]:
# Find the genre with avg highest IMDB rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [33]:
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].mean()['IMDB_Rating'].sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [34]:
# Find the director with most popularity
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [35]:
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [44]:
movies.groupby('Director')[movies.select_dtypes(include='number').columns].sum().sort_values('No_of_Votes',ascending=False).head(1)

                   Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Director
Christopher Nolan     1122         67.7     11578345  1.937454e+09      620.0

In [52]:
# Find the number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().value_counts().sort_values(ascending=False).head(1)

Series_Title
1    503
Name: count, dtype: int64

In [53]:
movies['Star1'].value_counts().sort_values(ascending=False)

Star1
Tom Hanks          12
Robert De Niro     11
Al Pacino          10
Clint Eastwood     10
Humphrey Bogart     9
                   ..
Barry Cook          1
Jason London        1
Jude Law            1
Cillian Murphy      1
Robert Donat        1
Name: count, Length: 660, dtype: int64

# Group Attributes and Methods

In [54]:
# Find toal number of group --->
len(movies.groupby('Genre'))

14

In [58]:
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [59]:
# first()/second()....nth()
movies.groupby('Genre').first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [60]:
movies.groupby('Genre').last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [65]:
movies.groupby('Genre').nth(6).set_index('Genre')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Star Wars: Episode V - The Empire Strikes Back,1980,124,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
Crime,Se7en,1995,127,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
Drama,It's a Wonderful Life,1946,130,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
Animation,WALL·E,2008,98,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
Comedy,The Great Dictator,1940,125,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
Biography,Braveheart,1995,178,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
Adventure,North by Northwest,1959,136,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
Mystery,Sleuth,1972,138,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
Horror,Get Out,2017,104,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [68]:
# get_group  ---> filtering
movies.groupby('Genre').get_group('Fantasy').set_index('Genre')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [72]:
movies[movies['Genre'] == 'Fantasy'].set_index('Genre')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [74]:
movies.groupby('Genre').get_group('Horror').set_index('Genre')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Horror,Alien,1979,117,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
Horror,The Thing,1982,109,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
Horror,The Exorcist,1973,122,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
Horror,Night of the Living Dead,1968,96,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
Horror,The Innocents,1961,100,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
Horror,Get Out,2017,104,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
Horror,Halloween,1978,91,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
Horror,The Invisible Man,1933,71,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
Horror,Saw,2004,103,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [82]:
movies[movies['Genre'] == 'Horror'].set_index('Genre')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Horror,Alien,1979,117,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
Horror,The Thing,1982,109,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
Horror,The Exorcist,1973,122,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
Horror,Night of the Living Dead,1968,96,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
Horror,The Innocents,1961,100,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
Horror,Get Out,2017,104,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
Horror,Halloween,1978,91,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
Horror,The Invisible Man,1933,71,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
Horror,Saw,2004,103,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [84]:
# describr
movies.groupby('Genre').describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [88]:
# sample
movies.groupby('Genre').sample(2,replace=True).set_index('Genre')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Bourne Identity,2002,119,7.9,Doug Liman,Franka Potente,508771,121661683.0,68.0
Action,Bonnie and Clyde,1967,111,7.8,Arthur Penn,Warren Beatty,102415,909838190.0,86.0
Adventure,Diarios de motocicleta,2004,126,7.8,Walter Salles,Gael García Bernal,96703,16756372.0,75.0
Adventure,The Gold Rush,1925,95,8.2,Charles Chaplin,Charles Chaplin,101053,5450000.0,NaN
Animation,Kubo and the Two Strings,2016,101,7.8,Travis Knight,Charlize Theron,118035,48023088.0,84.0
Animation,Spider-Man: Into the Spider-Verse,2018,117,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
Biography,The Big Short,2015,130,7.8,Adam McKay,Christian Bale,362942,70259870.0,81.0
Biography,Walk the Line,2005,136,7.8,James Mangold,Joaquin Phoenix,234207,119519402.0,72.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Comedy,Duck Soup,1933,69,7.8,Leo McCarey,Groucho Marx,55581,350197185.0,93.0
Crime,Death Note: Desu nôto,2006,126,7.7,Shûsuke Kaneko,Tatsuya Fujiwara,28630,207139906.0,NaN
Crime,Bound by Honor,1993,180,8.0,Taylor Hackford,Damian Chapa,28825,4496583.0,47.0
Drama,Casablanca,1942,102,8.5,Michael Curtiz,Humphrey Bogart,522093,1024560.0,100.0
Drama,Bridge of Spies,2015,142,7.6,Steven Spielberg,Tom Hanks,287659,72313754.0,81.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Halloween,1978,91,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Twelve Monkeys,1995,129,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
Mystery,Twelve Monkeys,1995,129,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,Once Upon a Time in the West,1968,165,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
Western,Once Upon a Time in the West,1968,165,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

In [89]:
# agg method
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].sum()

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [90]:
# using agg we can apply different aggregrate fucntions on different columns
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].agg(
{
    'Runtime':'mean',
    'IMDB_Rating':'mean',
    'No_of_Votes':'sum',
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [91]:
# using agg we can apply different aggregrate fucntions on different columns
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].agg(
{
    'Runtime':['mean','sum'],
    'IMDB_Rating':'mean',
    'No_of_Votes':'sum',
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime        IMDB_Rating No_of_Votes         Gross Metascore
                 mean    sum        mean         sum           sum       min
Genre
Action     129.046512  22196    7.949419    72282412  3.263226e+10      33.0
Adventure  134.111111   9656    7.937500    22576163  9.496922e+09      41.0
Animation   99.585366   8166    7.930488    21978630  1.463147e+10      61.0
Biography  136.022727  11970    7.938636    24006844  8.276358e+09      48.0
Comedy     112.129032  17380    7.901290    27620327  1.566387e+10      45.0
Crime      126.392523  13524    8.016822    33533615  8.452632e+09      47.0
Drama      124.737024  36049    7.957439    61367304  3.540997e+10      28.0
Family     107.500000    215    7.800000      551221  4.391106e+08      67.0
Fantasy     85.000000    170    8.000000      146222  7.827267e+08       NaN
Film-Noir  104.000000    312    7.966667      367215  1.259105e+08      94.0
Horror     102.090909   1123    7.909091     3742556  1.034649e+09      46.0
Mystery    119.083333   1429    7.975000     4203004  1.256417e+09      52.0
Thriller   108.000000    108    7.800000       27733  1.755074e+07      81.0
Western    148.250000    593    8.350000     1289665  5.822151e+07      69.0

In [92]:
# Using list
movies.groupby('Genre')[movies.select_dtypes(include='number').columns].agg(['min','max','sum','mean'])

          Runtime                         IMDB_Rating                         \
              min  max    sum        mean         min  max     sum      mean
Genre
Action         45  321  22196  129.046512         7.6  9.0  1367.3  7.949419
Adventure      88  228   9656  134.111111         7.6  8.6   571.5  7.937500
Animation      71  137   8166   99.585366         7.6  8.6   650.3  7.930488
Biography      93  209  11970  136.022727         7.6  8.9   698.6  7.938636
Comedy         68  188  17380  112.129032         7.6  8.6  1224.7  7.901290
Crime          80  229  13524  126.392523         7.6  9.2   857.8  8.016822
Drama          64  242  36049  124.737024         7.6  9.3  2299.7  7.957439
Family        100  115    215  107.500000         7.8  7.8    15.6  7.800000
Fantasy        76   94    170   85.000000         7.9  8.1    16.0  8.000000
Film-Noir     100  108    312  104.000000         7.8  8.1    23.9  7.966667
Horror         71  122   1123  102.090909         7.6  8.5    87.0  7.909091
Mystery        96  138   1429  119.083333         7.6  8.4    95.7  7.975000
Thriller      108  108    108  108.000000         7.8  7.8     7.8  7.800000
Western       132  165    593  148.250000         7.8  8.8    33.4  8.350000

          No_of_Votes                                          Gross  \
                  min      max       sum           mean          min
Genre
Action          25312  2303232  72282412  420246.581395       3296.0
Adventure       29999  1512360  22576163  313557.819444      61001.0
Animation       25229   999790  21978630  268032.073171     128985.0
Biography       27254  1213505  24006844  272805.045455      21877.0
Comedy          26337   939631  27620327  178195.658065       1305.0
Crime           27712  1826188  33533615  313398.271028       6013.0
Drama           25088  2343110  61367304  212343.612457       3600.0
Family         178731   372490    551221  275610.500000    4000000.0
Fantasy         57428    88794    146222   73111.000000  337574718.0
Film-Noir       59556   158731    367215  122405.000000     449191.0
Horror          27007   787806   3742556  340232.363636      89029.0
Mystery         33982  1129894   4203004  350250.333333    1035953.0
Thriller        27733    27733     27733   27733.000000   17550741.0
Western         65659   688390   1289665  322416.250000    5321508.0

                                                   Metascore                  \
                   max           sum          mean       min    max      sum
Genre
Action     936662225.0  3.263226e+10  1.897224e+08      33.0   98.0  10499.0
Adventure  874211619.0  9.496922e+09  1.319017e+08      41.0  100.0   5020.0
Animation  873839108.0  1.463147e+10  1.784326e+08      61.0   96.0   6082.0
Biography  753585104.0  8.276358e+09  9.404952e+07      48.0   97.0   6023.0
Comedy     886752933.0  1.566387e+10  1.010572e+08      45.0   99.0   9840.0
Crime      790482117.0  8.452632e+09  7.899656e+07      47.0  100.0   6706.0
Drama      924558264.0  3.540997e+10  1.225259e+08      28.0  100.0  19208.0
Family     435110554.0  4.391106e+08  2.195553e+08      67.0   91.0    158.0
Fantasy    445151978.0  7.827267e+08  3.913633e+08       NaN    NaN      0.0
Film-Noir  123353292.0  1.259105e+08  4.197018e+07      94.0   97.0    287.0
Horror     298791505.0  1.034649e+09  9.405902e+07      46.0   97.0    880.0
Mystery    474203697.0  1.256417e+09  1.047014e+08      52.0  100.0    633.0
Thriller    17550741.0  1.755074e+07  1.755074e+07      81.0   81.0     81.0
Western     31800000.0  5.822151e+07  1.455538e+07      69.0   90.0    313.0


                mean
Genre
Action     73.419580
Adventure  78.437500
Animation  81.093333
Biography  76.240506
Comedy     78.720000
Crime      77.080460
Drama      79.701245
Family     79.000000
Fantasy          NaN
Film-Noir  95.666667
Horror     80.000000
Mystery    79.125000
Thriller   81.000000
Western    78.250000